### ISSUE TITLE
No License?

### ISSUE THREAD

**Issue by rbtylee** [paaguti/debian_ta#1]
There is no license given. Am I safe in assuming it is GPL or some other FOSS license? While this repo does not really work I would like to use a few modified files here in my own Debian packaging of TA.

**Comment by paaguti** [comment]
Good point. Give me a couple of days to fix

/PA

Enviado desde mi iPhone

**Comment by rbtylee** [comment]
Thanks. When I get around to adding TA to Bodhi Linux's repos I will credit you for the files I modify and use in the Debian copyright. I usually add an email address if known in such a case.  Since yours is not public if you wish to share it email me. If I do not get an email from you I will assume you wish to keep it private. No worries either way.
